### ISSUE TITLE
"Cheat Engine through Steamtinkerlaunch"

### ISSUE THREAD

**Issue by frostworx** [KingKrouch/Cheat-Engine-Proton-Helper#1]
"The method of launching Cheat Engine through Steamtinkerlaunch [has been broken for a while](https://github.com/frostworx/steamtinkerlaunch/wiki/Cheat-Engine), and I needed to get a better way of doing this stuff siutuated."

It is not broken at all...

**Comment by frostworx** [comment]
.

**Comment by Naitrate** [comment]
I should have clarified a bit. I meant to say that the automatic downloading process was a bit borked at the time (many months ago) because of how Cheat Engine themselves distributes installers, and the documentation regarding checksums being a bit confusing.

Edited said quotation out of the Readme. I apologize for any beef that may have caused.
